/**
 * Typed registry of bundled illustration assets. Each is generated by the
 * OpenAI image pipeline (`scripts/generate-assets.ts`) and copied into
 * `apps/mobile/assets/illustrations/`. One import site so screens never reach
 * into asset paths directly. Imported (not required) so `expo/types` provides
 * the asset module typing.
 */
import welcomePeople from '../../assets/illustrations/welcome-people.png';
import authPhone from '../../assets/illustrations/auth-phone.png';
import authOtp from '../../assets/illustrations/auth-otp.png';
import authAgegate from '../../assets/illustrations/auth-agegate.png';

export const illustrations = {
  /** First-run welcome hero — four friends + floating interest badges. */
  welcomePeople,
  /** Phone-entry clay mascot — blob + phone + shield + padlock. */
  authPhone,
  /** OTP clay illustration — envelope + shield checkmark. */
  authOtp,
  /** Age-gate clay scene — friends on a couch with chat bubbles. */
  authAgegate,
} as const;

export type IllustrationKey = keyof typeof illustrations;
